### ISSUE TITLE
Add theaded TRIM calculations

### ISSUE THREAD

**Issue by dschwen** [idaholab/mytrim#32]
The main executable should use threading to accelerate calculations (this will make validation more convenient).

Main hurdle is random number generation, which uses static generators. I'll make those members of simconf.

**Comment by friedmud** [comment]
Good luck!  Threaded random number generation is difficult (assuming you want repeatable streams).

You could try to give every particle a unique ID (like the iteration index) and reseed based on that.  Just be aware that on OSX, if you're using `rand_r` the first few numbers that come out after a re-seed are _not_ random!

**Comment by dschwen** [comment]
Yeah, believe me, I'm aware of the difficulties. I'm not shooting for reproducibility between runs with different thread numbers (yet). I'll just give each thread its own instance of a `std::mt19937` and `std::uniform_real_distribution` :-)

**Comment by friedmud** [comment]
In that case: I'll warn you that non-deterministic software is a bitch to
debug....  ;-)

**Comment by dschwen** [comment]
Sure, fortunately the threading is going to be trivial compared to MOOSE. The MC algorithm is embarrassingly parallel.

**Comment by dschwen** [comment]
This has been solved in Magpie in a parallel reproducible way. Closing here.
