### ISSUE TITLE
Use cbrt

### ISSUE THREAD

**Issue by dschwen** [idaholab/mytrim#44]
Instead of `std::pow(x, 0.33333)` write `std::cbrt(x)`. It is over three times faster.

**Comment by dschwen** [comment]
Likewise use `x*x*x*x` instead of `std::pow(x, 4.0)` (over ten times faster!)

**Comment by friedmud** [comment]
BTW: libMesh has a handy template metaprogramming version of `pow` for integer powers:

https://github.com/libMesh/libmesh/blob/master/include/utils/utility.h#L194

You use it like so:

``` C++
Utility::pow<4>(some_double);
```

That would compute `some_double^4`

**Comment by dschwen** [comment]
Holy hell:

```
[~/Programs/mytrim/performance]> clang++ -std=c++11 pow4.C -o pow4 -O2
[~/Programs/mytrim/performance]> ./pow4
std::pow(x, 4.0) 333ms
x * x * x * x 20ms
pow<4>(x) 10ms
```
